### ISSUE TITLE
Creating a dataset without dates succeeds but then errors when searching

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/4cat#2]
It's possible to create a new Telegram dataset without specifying either a start or end date, but this then fails with an error when collecting starts. Specifically it complains that: `` No results. Error scraping posts from Telegram '>' not supported between instances of 'datetime.datetime' and 'NoneType'``

My gut feeling is that if collection is guaranteed to fail if dates are not provided then they should be made mandatory fields and you shouldn't be able to create the dataset without them. With them currently being optional I assumed that if left blank it would simply collect everything as it wouldn't add a date restriction.

**Comment by muneerahp** [comment]
Fixed. 

The order of "collection" (determined by original 4cat rather than me) is as follows (since useful for later adding to tooltip): The data is collected from the max date backwards, until either the max number of messages for that channel or the min date is hit (with the min date taking precedence in the event that it is set). 
If continuous collection is selected, it then switches to listening for new messages. At this point, it will stop if either the max date is hit (if set) or the stop button is set.
